### ISSUE TITLE
Problem Extending Transformer

### ISSUE THREAD

**Issue by tangjh** [octobroid/oc-api-plugin#2]
Got the following error returned from api when creating transformer following the given example:

    "error": {
        "code": "INTERNAL_ERROR",
        "http_code": 500,
        "message": "Cannot override final method Octobro\\API\\Classes\\Transformer::transform()"
    },

**Comment by triasrahman** [comment]
I'm sorry there is a mistake on documentation. It should be `data()` method instead of `transform()` method. Will update it soon.

**Comment by triasrahman** [comment]
Fixed in 0778df440626528c3103711f1681e8cc9c7d3f49
